// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostArgs struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId             string   `protobuf:"bytes,4,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArgs) Reset()         { *m = PostArgs{} }
func (m *PostArgs) String() string { return proto.CompactTextString(m) }
func (*PostArgs) ProtoMessage()    {}
func (*PostArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{0}
}

func (m *PostArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArgs.Unmarshal(m, b)
}
func (m *PostArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArgs.Marshal(b, m, deterministic)
}
func (m *PostArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArgs.Merge(m, src)
}
func (m *PostArgs) XXX_Size() int {
	return xxx_messageInfo_PostArgs.Size(m)
}
func (m *PostArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PostArgs proto.InternalMessageInfo

func (m *PostArgs) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostArgs) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostArgs) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostArgs) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type PostsReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsReply) Reset()         { *m = PostsReply{} }
func (m *PostsReply) String() string { return proto.CompactTextString(m) }
func (*PostsReply) ProtoMessage()    {}
func (*PostsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{1}
}

func (m *PostsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsReply.Unmarshal(m, b)
}
func (m *PostsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsReply.Marshal(b, m, deterministic)
}
func (m *PostsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsReply.Merge(m, src)
}
func (m *PostsReply) XXX_Size() int {
	return xxx_messageInfo_PostsReply.Size(m)
}
func (m *PostsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsReply.DiscardUnknown(m)
}

var xxx_messageInfo_PostsReply proto.InternalMessageInfo

func (m *PostsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PostArgs)(nil), "posts.PostArgs")
	proto.RegisterType((*PostsReply)(nil), "posts.PostsReply")
}

func init() {
	proto.RegisterFile("posts.proto", fileDescriptor_b14bd1586479c33d)
}

var fileDescriptor_b14bd1586479c33d = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc8, 0x2f, 0x2e,
	0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x64, 0xd2, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32,
	0xf3, 0xf3, 0xa0, 0x8a, 0x94, 0xf2, 0xb8, 0x38, 0x02, 0xf2, 0x8b, 0x4b, 0x1c, 0x8b, 0xd2, 0x8b,
	0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53,
	0x84, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0x42, 0x10, 0x8e, 0x90,
	0x02, 0x17, 0x77, 0x4a, 0x6a, 0x71, 0x72, 0x51, 0x66, 0x01, 0xc8, 0x1c, 0x09, 0x66, 0xb0, 0x1c,
	0xb2, 0x90, 0x90, 0x14, 0x17, 0x87, 0x63, 0x69, 0x49, 0x46, 0x7e, 0x91, 0x67, 0x8a, 0x04, 0x0b,
	0x58, 0x1a, 0xce, 0x57, 0x52, 0xe3, 0xe2, 0x02, 0xd9, 0x57, 0x1c, 0x94, 0x5a, 0x90, 0x53, 0x29,
	0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0xb5, 0x16, 0xc6, 0x35, 0xfa,
	0xce, 0x08, 0x71, 0x58, 0xb1, 0x63, 0x80, 0xa7, 0x90, 0x2f, 0x17, 0x57, 0x72, 0x51, 0x6a, 0x62,
	0x49, 0x2a, 0x48, 0x44, 0x88, 0x5f, 0x0f, 0xe2, 0x4b, 0x98, 0xbb, 0xa5, 0x04, 0x91, 0x04, 0x20,
	0x06, 0x2b, 0x49, 0x37, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x54, 0x49, 0x40, 0xbf, 0xcc, 0x50, 0x1f,
	0x2c, 0xab, 0x0f, 0x31, 0xc1, 0x8a, 0x51, 0x0b, 0x64, 0x5c, 0x4a, 0x6a, 0x4e, 0x2a, 0x65, 0xc6,
	0x41, 0x4c, 0x80, 0x1a, 0x57, 0x5a, 0x90, 0x42, 0xa1, 0xeb, 0x20, 0x26, 0x58, 0x31, 0x6a, 0x39,
	0xf1, 0x47, 0xf1, 0xea, 0xe9, 0x23, 0xc5, 0x63, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0x60, 0xe7, 0x2e, 0xdd, 0x01, 0x00, 0x00,
}
